/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shirotter' at '15/04/05 14:31' with Gradle 2.3
 *
 * @author shirotter, @date 15/04/05 14:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
